### ISSUE TITLE
Add Option to customize file names for html ,css and js files.

### ISSUE THREAD

**Issue by iamrajatg** [iamrajatg/bplate#1]

**Comment by cosmoimai** [comment]
Sir, Can I work on it

**Comment by iamrajatg** [comment]
> Sir, Can I work on it

Sure,Go Ahead 👍

**Comment by cosmoimai** [comment]
Sir Can we just provide the name in the terminal like using process.argv

**Comment by iamrajatg** [comment]
> Sir Can we just provide the name in the terminal like using process.argv

Yes we can

**Comment by cosmoimai** [comment]
@iamrajatg  Sir I have created PR
